version: '3.8'

services:
  postgres:
    build:
      context: ./database  # Usa o diretório atual para o build
      dockerfile: Dockerfile  # Especifica o Dockerfile a ser usado
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ict_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persistência de dados
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
